config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :blogs, only: %i[ index show new create ]
  resource :feed_items, only: %i[ show ]

  # Defines the root path route ("/")
  root "feed_items#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  attr_accessor :feed_urls

  has_many :feed_items, -> { order(published_at: :desc) }, dependent: :destroy

  validates_presence_of :url, :title, :description, :feed_url
  validate :is_valid_url

  scope :accepted, -> { where.not(accepted_at: nil) }
  scope :pending, -> { where(accepted_at: nil) }

  def accept!
    return unless accepted_at.nil?
    update! accepted_at: Time.current
  end

  def normalize_feed_url
    uri = URI.parse(feed_url)

    if uri.scheme.nil? || uri.host.nil?
      URI.join(url, feed_url).to_s
    else
      uri.to_s
    end
  rescue URI::InvalidURIError
    URI.join(url, feed_url).to_s
  end

  private
    def is_valid_url
      uri = URI.parse(url)

      unless uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS)
        errors.add(:url, "ha de ser HTTP o HTTPS")
      end

    rescue URI::InvalidURIError
      errors.add(:url, "no es válida")
    end
end

app/models/blog_data_from_url.rb
require "open-uri"
require "ostruct"

class BlogDataFromUrl
  def self.fetch(url)
    return unless url.present?

    html = URI.open(url)
    doc = Nokogiri::HTML(html)
    feed_urls = doc.css("link[type='application/rss+xml'], link[type='application/atom+xml']")
                  .map { |link|
                    OpenStruct.new(
                      title: link["title"],
                      url: link["href"]
                    )
                  }

    {
      url:,
      title: doc.at("title")&.text&.strip,
      description: doc.at("meta[name='description']")&.[]("content")&.strip,
      feed_urls:
    }
  rescue => e
    Rails.logger.error("[ERROR] => #{e.message}")

    {
      feed_urls: []
    }
  end
end

app/models/feed_item.rb
class FeedItem < ApplicationRecord
  belongs_to :blog

  validates_presence_of :title, :link, :guid, :published_at
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show ]

  def index
    @blogs = Blog.accepted.order(accepted_at: :desc)
  end

  def show
  end

  def new
    @blog = Blog.new(BlogDataFromUrl.fetch(params[:url]))
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: "Blog añadido correctamente. El proceso de revisión es manual, por lo que puede tardar unos días en aparecer públicamente."
    else
      @blog.feed_urls = BlogDataFromUrl.fetch(@blog.url)[:feed_urls]
      render :new, status: :unprocessable_entity
    end
  end

  private
    def set_blog
      @blog = Blog.find(params.expect(:id))
    end

    def blog_params
      params.expect(blog: [ :url, :title, :description, :feed_url, :accepted_at ])
    end
end

app/controllers/feed_items_controller.rb
class FeedItemsController < ApplicationController
  def show
    @feed_items = FeedItem.order(published_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <h2>
    <%= link_to_unless_current blog.title, blog_path(blog) %>
  </h2>

  <div>
    <%= simple_format blog.description %>
  </div>

  <% if blog.url.present? %>
    <p><%= link_to "Visitar blog", blog.url, target: "_blank" %></p>
  <% end %>
</div>

app/views/blogs/_form.html.erb
<% if !@blog.url %>

  <%= form_with(url: new_blog_path, method: :get) do |form| %>
    <div>
      <%= form.label :url, "URL", style: "display: block" %>
      <%= form.text_field :url %>
    </div>

    <div>
      <%= form.submit "Buscar", name: nil %>
    </div>
  <% end %>

<% else %>

  <%= form_with(model: @blog) do |form| %>
    <% if blog.errors.any? %>
      <div style="color: red">
        <ul>
          <% blog.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :url, style: "display: block" %>
      <%= form.text_field :url %>
    </div>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.textarea :description %>
    </div>

    <div>
      <%= form.label :feed_urls, style: "display: block" %>
      <ul>
        <%= form.collection_radio_buttons :feed_url, blog.feed_urls, :url, :title do |feed| %>
          <li>
            <%= feed.label do %>
              <%= feed.radio_button %>
              <%= feed.text %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>

    <div>
      <%= form.submit name: nil %>
    </div>
  <% end %>

<% end %>

app/views/blogs/index.html.erb
<% content_for :title, "Blogs" %>

<h1><%= content_for :title %></h1>

<%= link_to "Añadir blog", new_blog_path %>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
  <% end %>
</div>

app/views/blogs/new.html.erb
<% content_for :title, "Añadir blog" %>

<h1><%= content_for :title %></h1>

<%= render "form", blog: @blog %>

app/views/blogs/show.html.erb
<%= render @blog %>

app/views/common/_menu.html.erb
<nav class="menu">
  <ul>
    <li><%= link_to_unless_current "Inicio", root_path %></li>
    <li><%= link_to_unless_current "Blogs", blogs_path %></li>
  </ul>
</nav>

app/views/feed_items/show.html.erb
<h1>Últimas actualizaciones</h1>

<% @feed_items.each do |item| %>
  <div>
    <h2><%= link_to item.title, item.link %></h2>
    <div>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="heroicon">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9.004 9.004 0 0 0 8.716-6.747M12 21a9.004 9.004 0 0 1-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 0 1 7.843 4.582M12 3a8.997 8.997 0 0 0-7.843 4.582m15.686 0A11.953 11.953 0 0 1 12 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0 1 21 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0 1 12 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 0 1 3 12c0-1.605.42-3.113 1.157-4.418" />
        </svg>
        <%= item.blog.title %>
      </span>

      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="heroicon">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
        </svg>
        <%= t(item.published_at, format: :short) %>
      </span>
    </div>
    <hr />
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blogs Personales" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "common/menu" %>
    <%= yield %>
  </body>
</html>